# -*- coding:utf-8 -*-
# Created by l00ng at 2017/5/3

s='''ZWAXJGDLUBVIQHKYPNTCRMOSFE
KPBELNACZDTRXMJQOYHGVSFUWI
BDMAIZVRNSJUWFHTEQGYXPLOCK
RPLNDVHGFCUKTEBSXQYIZMJWAO
IHFRLABEUOTSGJVDKCPMNZQWXY
AMKGHIWPNYCJBFZDRUSLOQXVET
GWTHSPYBXIZULVKMRAFDCEONJQ
NOZUTWDCVRJLXKISEFAPMYGHBQ
QWATDSRFHENYVUBMCOIKZGJXPL
WABMCXPLTDSRJQZGOIKFHENYVU
XPLTDAOIKFZGHENYSRUBMCQWVJ
TDSWAYXPLVUBOIKZGJRFHENMCQ
BMCSRFHLTDENQWAOXPYVUIKZGJ
XPHKZGJTDSENYVUBMLAOIRFCQW'''

x= s.split('\n')

key = '2,5,1,3,6,4,9,7,8,14,10,13,11,12'.split(',')

str = 'HCBTSXWCRQGLES'

o=[]

for i in range(0,len(str),1):
    o.append(str[i]+x[int(key[i])-1].split(str[i])[1]+x[int(key[i])-1].split(str[i])[0])

for i in range(0,26,1):
    k=''
    for j in range(0, len(str), 1):
        k = k + o[j][i]
    print k
